eureka:
  client:
    service-url:
      defaultZone: ${eureka.server}
  #    register-with-eureka: false
  server:
    enable-self-preservation: false
spring:
  application:
    name: eureka
server:
  port: 8762