eureka:
  instance:
    hostname: eureka-slave1
  client:
    service-url:
      defaultZone: http://eureka-master:8761/eureka/,http://eureka-slave2:8763/eureka/
  #自我保护机制
  server:
    enable-self-preservation: false
server:
  port: 8762