eureka:
  client:
    service-url:
      defaultZone: http://eureka1:8761/eureka/,http://eureka2:8762/eureka/
  #自我保护机制
  server:
    enable-self-preservation: false
server:
  port: 8763
spring:
  application:
    name: eureka